### ISSUE TITLE
报错：invalid option -- '-' File: stdin.png!?

### ISSUE THREAD

**Issue by dante1977** [xiangshouding/node-pngquant-native#14]
![image](https://cloud.githubusercontent.com/assets/5715397/17364942/c55b3878-59b5-11e6-84a6-a0ca0a004233.png)
如上：被压缩的那张图片，是用[node-images](https://github.com/zhangyuanwei/node-images.git)生成的

**Comment by xiangshouding** [comment]
你用的时候是不是传了什么参数？

**Comment by dante1977** [comment]
![image](https://cloud.githubusercontent.com/assets/5715397/17393209/cdf04fe2-5a54-11e6-993a-f0619af3ea6d.png)
应该没有吧，就这两个参数

**Comment by xiangshouding** [comment]
这个不科学啊
