### ISSUE TITLE
does not support your node v4.4.4 in window7

### ISSUE THREAD

**Issue by jiajianrong** [xiangshouding/node-pngquant-native#19]
```
 [WARNI] node-pngquant-native does not support your node v4.4.4, report it to ht
tps://github.com/xiangshouding/node-pngquant-native/issues
```

请问如下配置有什么问题吗？我用的是node4.4.4和jello1.0.7

```
"dependencies": {
    "fis-parser-node-sass": "0.2.1",
    "fis-parser-utc": "0.0.2",
    "fis-parser-es6-2-es5": "^2.2.0",
    "fis-postpackager-framework-trace": "^1.1.1",
    "jello": "1.0.7",
    "jello-postpackager-require-framework": "^4.0.0",
    "jello-postpackager-vmparse": "^1.1.0",
    "jello-preprocessor-vmparse": "^5.0.0"
  }
```

**Comment by xiangshouding** [comment]
安装没啥问题么？感觉是安装没有下载对应的 bindings
jiajianrong <notifications@github.com>于2017年5月16日 周二下午9:42写道：

**Comment by jiajianrong** [comment]
我uninstall了再试试，当时在cnpm install的时候没注意看
我现在试了确实图片不压缩了

**Comment by jiajianrong** [comment]
`E:\LS_spec\fe_dev>cnpm install -g f8
[fsevents@0.3.8](D:\node\node-global\node_modules\.f8_npminstall\node_modules\.1
.0.3@chokidar\node_modules\fsevents) unsupported: Package require os(darwin) not
 compatible with your platform(win32)
[fsevents@^0.3.1] optional install error: Package require os(darwin) not compati
ble with your platform(win32)
[minimatch@0.2.14](D:\node\node-global\node_modules\.f8_npminstall\node_modules\
.1.4.0@readdirp\node_modules\minimatch) deprecate: Please update to minimatch 3.
0.2 or higher to avoid a RegExp DoS issue
[ignore@2.2.7](D:\node\node-global\node_modules\.f8_npminstall\node_modules\.0.1
.14@fis-repo-client\node_modules\ignore) deprecate: several bugs fixed in v3.2.1

[node-uuid@1.4.8](D:\node\node-global\node_modules\.f8_npminstall\node_modules\.
2.27.0@request\node_modules\node-uuid) deprecate: Use uuid module instead
[minimatch@2.0.10](D:\node\node-global\node_modules\.f8_npminstall\node_modules\
.5.8.38@babel-core\node_modules\minimatch) deprecate: Please update to minimatch
 3.0.2 or higher to avoid a RegExp DoS issue
[f8@1.0.1] link D:\node\node-global\f8@ -> D:\node\node-global\f8
[f8@*] installed at node_modules\.f8_npminstall\node_modules\.1.0.1@f8 (464 pack
ages, use 34s, speed 22.23kB/s, json 757.9kB, tarball 0B)
execute post install scripts...
[node-pngcrush@0.2.0] scripts.install: "echo \"Hello, World.\"" at D:\node\node-
global\node_modules\.f8_npminstall\node_modules\.0.2.0@node-pngcrush
"Hello, World."
[node-pngcrush@0.2.0] scripts.install success, use 33ms
[images@2.1.5] scripts.install: "echo \"Hello, World.\"" at D:\node\node-global\
node_modules\.f8_npminstall\node_modules\.2.1.5@images
"Hello, World."
[images@2.1.5] scripts.install success, use 18ms
[node-pngquant-native@0.2.2] scripts.install: "echo \"Hello, World\"" at D:\node
\node-global\node_modules\.f8_npminstall\node_modules\.0.2.2@node-pngquant-nativ
e
"Hello, World"
[node-pngquant-native@0.2.2] scripts.install success, use 24ms
[node-sass@3.7.0] scripts.install: "node scripts/install.js" at D:\node\node-glo
bal\node_modules\.f8_npminstall\node_modules\.3.7.0@node-sass
Binary downloaded and installed at D:\node\node-global\node_modules\.f8_npminsta
ll\node_modules\.3.7.0@node-sass\vendor\win32-x64-46\binding.node
[node-sass@3.7.0] scripts.install success, use 5s
[node-sass@3.7.0] scripts.postinstall: "node scripts/build.js" at D:\node\node-g
lobal\node_modules\.f8_npminstall\node_modules\.3.7.0@node-sass
"D:\node\node-global\node_modules\.f8_npminstall\node_modules\.3.7.0@node-sass\v
endor\win32-x64-46\binding.node" exists.
 testing binary.
Binary is fine; exiting.
[node-sass@3.7.0] scripts.postinstall success, use 361ms
All packages installed (464 packages installed from npm registry, use 40s, speed
 19.1kB/s, json 521(757.9kB), tarball 0B)`

**Comment by jiajianrong** [comment]
```
E:\LS_spec\fe_dev>cnpm install -g f8
[fsevents@0.3.8](D:\node\node-global\node_modules\.f8_npminstall\node_modules\.1
.0.3@chokidar\node_modules\fsevents) unsupported: Package require os(darwin) not
 compatible with your platform(win32)
[fsevents@^0.3.1] optional install error: Package require os(darwin) not compati
ble with your platform(win32)
[minimatch@0.2.14](D:\node\node-global\node_modules\.f8_npminstall\node_modules\
.1.4.0@readdirp\node_modules\minimatch) deprecate: Please update to minimatch 3.
0.2 or higher to avoid a RegExp DoS issue
[ignore@2.2.7](D:\node\node-global\node_modules\.f8_npminstall\node_modules\.0.1
.14@fis-repo-client\node_modules\ignore) deprecate: several bugs fixed in v3.2.1

[node-uuid@1.4.8](D:\node\node-global\node_modules\.f8_npminstall\node_modules\.
2.27.0@request\node_modules\node-uuid) deprecate: Use uuid module instead
[minimatch@2.0.10](D:\node\node-global\node_modules\.f8_npminstall\node_modules\
.5.8.38@babel-core\node_modules\minimatch) deprecate: Please update to minimatch
 3.0.2 or higher to avoid a RegExp DoS issue
[f8@1.0.1] link D:\node\node-global\f8@ -> D:\node\node-global\f8
[f8@*] installed at node_modules\.f8_npminstall\node_modules\.1.0.1@f8 (464 pack
ages, use 34s, speed 22.23kB/s, json 757.9kB, tarball 0B)
execute post install scripts...
[node-pngcrush@0.2.0] scripts.install: "echo \"Hello, World.\"" at D:\node\node-
global\node_modules\.f8_npminstall\node_modules\.0.2.0@node-pngcrush
"Hello, World."
[node-pngcrush@0.2.0] scripts.install success, use 33ms
[images@2.1.5] scripts.install: "echo \"Hello, World.\"" at D:\node\node-global\
node_modules\.f8_npminstall\node_modules\.2.1.5@images
"Hello, World."
[images@2.1.5] scripts.install success, use 18ms
[node-pngquant-native@0.2.2] scripts.install: "echo \"Hello, World\"" at D:\node
\node-global\node_modules\.f8_npminstall\node_modules\.0.2.2@node-pngquant-nativ
e
"Hello, World"
[node-pngquant-native@0.2.2] scripts.install success, use 24ms
[node-sass@3.7.0] scripts.install: "node scripts/install.js" at D:\node\node-glo
bal\node_modules\.f8_npminstall\node_modules\.3.7.0@node-sass
Binary downloaded and installed at D:\node\node-global\node_modules\.f8_npminsta
ll\node_modules\.3.7.0@node-sass\vendor\win32-x64-46\binding.node
[node-sass@3.7.0] scripts.install success, use 5s
[node-sass@3.7.0] scripts.postinstall: "node scripts/build.js" at D:\node\node-g
lobal\node_modules\.f8_npminstall\node_modules\.3.7.0@node-sass
"D:\node\node-global\node_modules\.f8_npminstall\node_modules\.3.7.0@node-sass\v
endor\win32-x64-46\binding.node" exists.
 testing binary.
Binary is fine; exiting.
[node-sass@3.7.0] scripts.postinstall success, use 361ms
All packages installed (464 packages installed from npm registry, use 40s, speed
 19.1kB/s, json 521(757.9kB), tarball 0B)
```

**Comment by jiajianrong** [comment]
貌似还是不行，但我看`node-pngquant-native`相关的没有报错啊

**Comment by jiajianrong** [comment]
卸载了再 用 --no-cache 就可以了，应该是安装的时候出了问题
