### ISSUE TITLE
node v.8.9.4 not support

### ISSUE THREAD

**Issue by jackrouse** [xiangshouding/node-pngquant-native#24]
[WARNI] node-pngquant-native does not support your node v8.9.4, report it to ht ps://github.com/xiangshouding/node-pngquant-native/issues

**Comment by xiangshouding** [comment]
安装最新的了么，另外什么系统？

**Comment by gongph** [comment]
遇到同样的问题，开发环境如下：
1. win7
2. Node v8.9.4
3. Npm v5.6.0
4. Fis3 v3.4.39

**Comment by xiangshouding** [comment]
![image](https://user-images.githubusercontent.com/631195/39391117-2753e062-4ad1-11e8-9f19-d4d610c199c9.png)

擦，忘了，貌似确实还没有支持上，windows 的，可以选择用 pngcrush。

**Comment by gongph** [comment]
擦，加上呗。

**Comment by xiangshouding** [comment]
看看这周周末有时间弄一下

**Comment by dcchan** [comment]
v8.11.2 提示 does not support your node。Mac系统

**Comment by xiangshouding** [comment]
@dcchan 下载成功了么？
