### ISSUE TITLE
 does not support your node v9.4.0

### ISSUE THREAD

**Issue by liuyankai1990** [xiangshouding/node-pngquant-native#26]
node-pngquant-native does not support your node v9.4.0, report it to https://github.com/xiangshouding/node-pngquant-native/issues

mac系统 是否不支持9.4.0版本的node

**Comment by liuyankai1990** [comment]
我改成V8.11.2 依然不支持。。。。是我的姿势不对吗
node-pngquant-native does not support your node v8.11.2, report it to https://github.com/xiangshouding/node-pngquant-native/issues

**Comment by 2betop** [comment]
需要重新安装

**Comment by liuyankai1990** [comment]
重新安装node-pngquant-native吗？

**Comment by langjun** [comment]
遇到同样问题
---
Node version v9.90

![image](https://user-images.githubusercontent.com/7370806/42254713-a01ca604-7f7a-11e8-9216-05a04006f83c.png)

**Comment by xiangshouding** [comment]
Node 9.x 还现在还不支持。

**Comment by gongph** [comment]
> Node 9.x 还现在还不支持。

怪不得 `fis.plugin('png-compressor')` 压缩图片在 `node@10.0.0+` 上报错了。。。
