### ISSUE TITLE
it's not work at node v0.12.0

### ISSUE THREAD

**Issue by jackness1208** [xiangshouding/node-pngquant-native#3]
This occurs when I execute “scrat release -opd ../output”

**Comment by xiangshouding** [comment]
scrat 还没有升级到最新的 fis 吧？只有最新的 fis 才支持 0.12.0

**Comment by guohaoxu** [comment]
"compress a buffer of .png" 这是什么意思啊？

**Comment by xiangshouding** [comment]
@guohaoxu spt 只是偶得作，可以联系作者升级到最新 fis ，然后就能在 0.12.x 下跑了。。
