### ISSUE TITLE
Node.js v10 tag and publish please.

### ISSUE THREAD

**Issue by jperdereau** [xiangshouding/node-pngquant-native#31]
Hello,

If you can tag and publish your latest commit https://github.com/xiangshouding/node-pngquant-native/commit/ed734be62b4d68306d29bf8de470046fb9832f83 that will wonderful.

Thx in advance.

**Comment by xiangshouding** [comment]
DONE
You can retry, thx!

Jeremie Perdereau <notifications@github.com> 于2020年4月23日周四 下午6:18写道：

**Comment by jperdereau** [comment]
Thx
