### ISSUE TITLE
每次都报这个异常

### ISSUE THREAD

**Issue by chenxiaochun** [xiangshouding/node-pngquant-native#5]
![image](https://cloud.githubusercontent.com/assets/1744713/7721271/ce92a204-ff08-11e4-9d99-07cf0b087e1c.png)
我的node版本是：0.12.3

**Comment by xiangshouding** [comment]
更新最新版本

**Comment by chenxiaochun** [comment]
我现在用的就是最新版本
![image](https://cloud.githubusercontent.com/assets/1744713/7721428/1f568ba0-ff0a-11e4-8867-7ba299149c77.png)

**Comment by xiangshouding** [comment]
如果是的系统是 64 的那么你就得装 64 的 Node，不然就是会有加载问题；

**Comment by chenxiaochun** [comment]
有道理，我试试。

**Comment by xiangshouding** [comment]
@chenxiaochun 那你先降级 node 用着，我看看这个问题；是否在我的机器上能复现；
