### ISSUE TITLE
Need to update to nan 2.x.x

### ISSUE THREAD

**Issue by micky2be** [xiangshouding/node-pngquant-native#6]
For essentially **iojs 3** compatibility.

**Comment by ChALkeR** [comment]
Adding to the list: https://github.com/nodejs/node/issues/2798.

**Comment by micky2be** [comment]
Well Node can't much for you if you don't update your dependency.
It wasn't working already with Node 3.x

**Comment by xiangshouding** [comment]
Thanks, i will soon make an upgrade
